### ISSUE TITLE
Breach of license agreement

### ISSUE THREAD

**Issue by flexpaper** [hivsuper/MyFlexPaperViewer#1]
This project is in breach of our license agreement. As according to the GPLv3 with additional branding details, you are not allowed to remove our logo from the viewer. Please correct this or we will have to submit a takedown notice to github

**Comment by hivsuper** [comment]
Sorry for replying your message so late. I didn't mean to breach of your license agreement when taking some test base on the project. I sincerely apologize for what i did and I am deleting this project now.
